2025-10-17 11:18:01.071 | INFO     | app.core.logging_config:setup_logging:60 - Configuração de logging concluída e interceptadores ativados.
2025-10-17 11:18:05.792 | INFO     | main:log_requests:47 - Request: GET /api/v1/users/ | Status: 200 | Duration: 223.72ms
2025-10-17 11:18:05.808 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 0.45ms
2025-10-17 11:18:05.826 | INFO     | main:log_requests:47 - Request: GET /api/v1/users/ | Status: 200 | Duration: 0.60ms
2025-10-17 11:18:05.826 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 0.00ms
2025-10-17 11:18:07.296 | INFO     | main:log_requests:47 - Request: GET /api/v1/users/me | Status: 200 | Duration: 2.00ms
2025-10-17 11:18:07.300 | INFO     | main:log_requests:47 - Request: GET /api/v1/users/me | Status: 200 | Duration: 2.00ms
2025-10-17 11:18:07.367 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 2.70ms
2025-10-17 11:18:07.369 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 0.00ms
2025-10-17 11:18:19.616 | INFO     | main:log_requests:47 - Request: GET /api/v1/users/me | Status: 401 | Duration: 0.00ms
2025-10-17 11:18:19.618 | INFO     | main:log_requests:47 - Request: GET /api/v1/users/me | Status: 401 | Duration: 1.01ms
2025-10-17 11:18:27.048 | DEBUG    | logging:callHandlers:1706 - Calling on_field_start with no data
2025-10-17 11:18:27.048 | DEBUG    | logging:callHandlers:1706 - Calling on_field_name with data[0:8]
2025-10-17 11:18:27.048 | DEBUG    | logging:callHandlers:1706 - Calling on_field_data with data[9:27]
2025-10-17 11:18:27.048 | DEBUG    | logging:callHandlers:1706 - Calling on_field_end with no data
2025-10-17 11:18:27.048 | DEBUG    | logging:callHandlers:1706 - Calling on_field_start with no data
2025-10-17 11:18:27.048 | DEBUG    | logging:callHandlers:1706 - Calling on_field_name with data[28:36]
2025-10-17 11:18:27.048 | DEBUG    | logging:callHandlers:1706 - Calling on_field_data with data[37:45]
2025-10-17 11:18:27.048 | DEBUG    | logging:callHandlers:1706 - Calling on_field_end with no data
2025-10-17 11:18:27.048 | DEBUG    | logging:callHandlers:1706 - Calling on_end with no data
2025-10-17 11:18:27.048 | WARNING  | logging:callHandlers:1706 - (trapped) error reading bcrypt version
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 428
               │     └ 3
               └ <function _main at 0x0000026022F30180>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 133, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 428
           │    └ <function BaseProcess._bootstrap at 0x0000026022E45D00>
           └ <SpawnProcess name='SpawnProcess-10' parent=16052 started>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x0000026022E45260>
    └ <SpawnProcess name='SpawnProcess-10' parent=16052 started>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x0000026022F03210>, 'target': <bound method Server.run of <uvicorn.server.Server...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-10' parent=16052 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-10' parent=16052 started>
    │    └ <function subprocess_started at 0x0000026025301E40>
    └ <SpawnProcess name='SpawnProcess-10' parent=16052 started>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=504, family=2, type=1, proto=6, laddr=('127.0.0.1', 8000)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x000002602548F550>>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ [<socket.socket fd=504, family=2, type=1, proto=6, laddr=('127.0.0.1', 8000)>]
           │       │   │    └ <function Server.serve at 0x0000026025300D60>
           │       │   └ <uvicorn.server.Server object at 0x000002602548F550>
           │       └ <function run at 0x0000026024B30C20>
           └ <module 'asyncio' from 'C:\\Users\\Vitor Lemes\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object Server.serve at 0x000002602542E980>
           │      └ <function Runner.run at 0x0000026024BB8B80>
           └ <asyncio.runners.Runner object at 0x000002602548EA10>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Server.serve() running at C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000026024BBE660>
           │    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000002602548EA10>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x0000026024BBE5C0>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 604, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000026024BB8400>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000026024AE9F80>
    └ <Handle Task.task_wakeup(<Future finis...ECT 1', True)>)>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finis...ECT 1', True)>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finis...ECT 1', True)>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis...ECT 1', True)>)>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
          │    │   │      │                      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.send_no_error at 0x0000026028701260>
          │    │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x000002602928B920>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x0000026028B71350>
          └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x00000260284A4DD0>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.send_no_error at 0x0000026028701260>
          │                            │    │    │     │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x000002602928B920>
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    │    └ <starlette.requests.Request object at 0x0000026029279C50>
          │                            │    └ <fastapi.routing.APIRouter object at 0x0000026028895410>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x0000026028B71350>
          └ <function wrap_app_handling_exceptions at 0x000002602642A8E0>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000026028DBB920>
          │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x000002602928B920>
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <fastapi.routing.APIRouter object at 0x0000026028895410>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000026028DBB920>
          │    │                │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x000002602928B920>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x0000026028895410>>
          └ <fastapi.routing.APIRouter object at 0x0000026028895410>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000026028DBB920>
          │     │      │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x000002602928B920>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0x00000260264580E0>
          └ APIRoute(path='/api/v1/login/access-token', name='login_access_token', methods=['POST'])
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000026028DBB920>
          │    │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x000002602928B920>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0x0000026028C26C00>
          └ APIRoute(path='/api/v1/login/access-token', name='login_access_token', methods=['POST'])
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000026028DBB920>
          │                            │    │        │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x000002602928B920>
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │                            │    └ <starlette.requests.Request object at 0x0000026028DC5890>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x0000026028DB8CC0>
          └ <function wrap_app_handling_exceptions at 0x000002602642A8E0>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x0000026028DB91C0>
          │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x000002602928B920>
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.4'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          └ <function request_response.<locals>.app.<locals>.app at 0x0000026028DB8CC0>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x0000026028DC5890>
                     └ <function get_request_handler.<locals>.app at 0x0000026028C26DE0>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x0000026022CC4860>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'db': <sqlalchemy.orm.session.AsyncSession object at 0x00000260293B2650>, 'form_data': <fastapi.security.oauth2.OAuth2Passwo...
                 │         └ <function login_access_token at 0x0000026028864220>
                 └ <fastapi.dependencies.models.Dependant object at 0x0000026028C71690>

  File "C:\Users\Vitor Lemes\Downloads\VRSales\api\app\api\endpoints\login.py", line 23, in login_access_token
    user = await crud.user.authenticate(
                 │    │    └ <function CRUDUser.authenticate at 0x0000026028703060>
                 │    └ <app.crud.crud_user.CRUDUser object at 0x0000026028731A90>
                 └ <module 'app.crud' from 'C:\\Users\\Vitor Lemes\\Downloads\\VRSales\\api\\app\\crud\\__init__.py'>

  File "C:\Users\Vitor Lemes\Downloads\VRSales\api\app\crud\crud_user.py", line 27, in authenticate
    if not verify_password(password, user.hashed_password):
           │               │         │    └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x0000026027FD5D00>
           │               │         └ <app.models.user.User object at 0x00000260293C8950>
           │               └ '12345678'
           └ <function verify_password at 0x00000260282671A0>

  File "C:\Users\Vitor Lemes\Downloads\VRSales\api\app\core\security.py", line 13, in verify_password
    return pwd_context.verify(plain_password, hashed_password)
           │           │      │               └ '$2b$12$lReHdcGVdUzPqUJigAEObur9s6cWFohXkPt0N66zoUPsHXtAbhake'
           │           │      └ '12345678'
           │           └ <function CryptContext.verify at 0x0000026028266840>
           └ <CryptContext at 0x260281927d0>

  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\passlib\context.py", line 2347, in verify
    return record.verify(secret, hash, **kwds)
           │      │      │       │       └ {}
           │      │      │       └ '$2b$12$lReHdcGVdUzPqUJigAEObur9s6cWFohXkPt0N66zoUPsHXtAbhake'
           │      │      └ '12345678'
           │      └ <classmethod(<function GenericHandler.verify at 0x0000026028234180>)>
           └ <class 'passlib.handlers.bcrypt.<customized bcrypt hasher>'>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\passlib\utils\handlers.py", line 792, in verify
    return consteq(self._calc_checksum(secret), chk)
           │       │    │              │        └ 'r9s6cWFohXkPt0N66zoUPsHXtAbhake'
           │       │    │              └ '12345678'
           │       │    └ <function _NoBackend._calc_checksum at 0x00000260284B8900>
           │       └ <passlib.handlers.bcrypt.<customized bcrypt hasher> object at 0x00000260293B1290>
           └ <built-in function compare_digest>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\passlib\handlers\bcrypt.py", line 591, in _calc_checksum
    self._stub_requires_backend()
    │    └ <classmethod(<function BackendMixin._stub_requires_backend at 0x0000026028236480>)>
    └ <passlib.handlers.bcrypt.<customized bcrypt hasher> object at 0x00000260293B1290>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\passlib\utils\handlers.py", line 2254, in _stub_requires_backend
    cls.set_backend()
    │   └ <classmethod(<function BackendMixin.set_backend at 0x0000026028236200>)>
    └ <class 'passlib.handlers.bcrypt.<customized bcrypt hasher>'>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\passlib\utils\handlers.py", line 2156, in set_backend
    return owner.set_backend(name, dryrun=dryrun)
           │     │           │            └ False
           │     │           └ 'any'
           │     └ <classmethod(<function BackendMixin.set_backend at 0x0000026028236200>)>
           └ <class 'passlib.handlers.bcrypt.bcrypt'>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\passlib\utils\handlers.py", line 2163, in set_backend
    return cls.set_backend(name, dryrun=dryrun)
           │   │           │            └ False
           │   │           └ 'bcrypt'
           │   └ <classmethod(<function BackendMixin.set_backend at 0x0000026028236200>)>
           └ <class 'passlib.handlers.bcrypt.bcrypt'>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\passlib\utils\handlers.py", line 2188, in set_backend
    cls._set_backend(name, dryrun)
    │   │            │     └ False
    │   │            └ 'bcrypt'
    │   └ <classmethod(<function SubclassBackendMixin._set_backend at 0x00000260282365C0>)>
    └ <class 'passlib.handlers.bcrypt.bcrypt'>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\passlib\utils\handlers.py", line 2311, in _set_backend
    super(SubclassBackendMixin, cls)._set_backend(name, dryrun)
          │                     │                 │     └ False
          │                     │                 └ 'bcrypt'
          │                     └ <class 'passlib.handlers.bcrypt.bcrypt'>
          └ <class 'passlib.utils.handlers.SubclassBackendMixin'>
  File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\passlib\utils\handlers.py", line 2224, in _set_backend
    ok = loader(**kwds)
         │        └ {'name': 'bcrypt', 'dryrun': False}
         └ <bound method _BcryptBackend._load_backend_mixin of <class 'passlib.handlers.bcrypt._BcryptBackend'>>
> File "C:\Users\Vitor Lemes\AppData\Local\Programs\Python\Python311\Lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              └ <module 'bcrypt' from 'C:\\Users\\Vitor Lemes\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\bcrypt\\__ini...

AttributeError: module 'bcrypt' has no attribute '__about__'
2025-10-17 11:18:27.080 | DEBUG    | logging:callHandlers:1706 - detected 'bcrypt' backend, version '<unknown>'
2025-10-17 11:18:27.080 | DEBUG    | logging:callHandlers:1706 - 'bcrypt' backend lacks $2$ support, enabling workaround
2025-10-17 11:18:27.330 | INFO     | main:log_requests:47 - Request: POST /api/v1/login/access-token | Status: 200 | Duration: 282.39ms
2025-10-17 11:18:27.330 | INFO     | main:log_requests:47 - Request: GET /api/v1/users/me | Status: 200 | Duration: 0.00ms
2025-10-17 11:18:30.551 | INFO     | main:log_requests:47 - Request: GET /api/v1/users/ | Status: 200 | Duration: 2.56ms
2025-10-17 11:18:30.553 | INFO     | main:log_requests:47 - Request: GET /api/v1/users/ | Status: 200 | Duration: 0.00ms
2025-10-17 11:18:31.185 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 0.00ms
2025-10-17 11:18:31.185 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 0.00ms
2025-10-17 11:18:35.042 | INFO     | main:log_requests:47 - Request: GET /api/v1/users/me | Status: 200 | Duration: 2.45ms
2025-10-17 11:18:35.045 | INFO     | main:log_requests:47 - Request: GET /api/v1/users/me | Status: 200 | Duration: 2.00ms
2025-10-17 11:18:35.154 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 3.99ms
2025-10-17 11:18:35.159 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 4.01ms
2025-10-17 11:19:22.651 | INFO     | main:log_requests:47 - Request: GET /api/v1/users/me | Status: 200 | Duration: 3.12ms
2025-10-17 11:19:22.658 | INFO     | main:log_requests:47 - Request: GET /api/v1/users/me | Status: 200 | Duration: 3.00ms
2025-10-17 11:19:22.906 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 3.01ms
2025-10-17 11:19:22.909 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 2.25ms
2025-10-17 11:19:22.956 | INFO     | main:log_requests:47 - Request: GET /api/v1/users/me | Status: 200 | Duration: 2.00ms
2025-10-17 11:19:22.959 | INFO     | main:log_requests:47 - Request: GET /api/v1/users/me | Status: 200 | Duration: 0.00ms
2025-10-17 11:19:23.099 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 3.00ms
2025-10-17 11:19:23.102 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 0.00ms
2025-10-17 11:20:16.043 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 0.00ms
2025-10-17 11:20:16.056 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 12.94ms
2025-10-17 11:20:18.978 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 2.89ms
2025-10-17 11:20:18.982 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 1.95ms
2025-10-17 11:21:12.665 | INFO     | main:log_requests:47 - Request: GET /api/v1/tables/ | Status: 200 | Duration: 0.00ms
